### ISSUE TITLE
Outputting function as root dd/dump object does not behave consistently

### ISSUE THREAD

**Issue by brodriguez8774** [DJBarnes/django-dump-die#13]
Seems to be related to call-stack examination.

Currently seems to (generally) output correctly for module-level functions, but breaks with class-level.

Before closing issue, should also examine functions in nested classes, as well as outputting a default value in event of future call-stack examination issues.

**Comment by DJBarnes** [comment]
Currently works when dumping a function and a function on an object. But fails to find the function name if the function is deeper within an object. EX: dump(obj_a.prop_b.do_work) will not be able to find the name of do_work. But, should we really be dumping things in this manner anyway? It seems more likely to just dump obj_a and then inspect.

**Comment by DJBarnes** [comment]
Was determined that they should be functionality that is included. Should be fully fixed as there is an entirely new way of getting the dumped variable's name that is way simpler and handles making nested calls inside the dump.
