### ISSUE TITLE
Error when dd-ing a function

### ISSUE THREAD

**Issue by brodriguez8774** [DJBarnes/django-dump-die#17]
Trying to dd a function works.
Trying to dd a function AND actively call the function in the same line appears to raise an error.

Appears to (maybe?) be an issue trying to parse "obj" (aka function) name.

Gives "EOF in multi-line statement" tokenize.TokenError.
Occurs in django_dump_die/utils.py, process_object_name(), line 119.

**Comment by DJBarnes** [comment]
So, are you trying to dump the result of a function call? Just trying to make sure I understand. I would expect this to have weird side effects due to how it tries to get the name of the object being dumped. Since it is the result of a function call, it has no name.

**Comment by DJBarnes** [comment]
This should be fixed via the fix_function_dump_error branch. Would like some verification before closing as the solution is not the most elegant, but does work.

**Comment by brodriguez8774** [comment]
This appears to now be fully handled, properly tokenized, and merged into development.

If we end up finding further instances of params that break functions, we can reopen. Closing for now.
