### ISSUE TITLE
Error when dd-ing models.FileField attribute

### ISSUE THREAD

**Issue by brodriguez8774** [DJBarnes/django-dump-die#18]
Confirmed when trying to dd a ModelForm that is trying to process the FileField. Happened when FileField attribute was empty.

Suspect that it also happens when trying to dd the corresponding model instance itself, but unconfirmed as of submitting this issue.

**Comment by DJBarnes** [comment]
I'm pretty sure that this same error occurs with the ImageField. Probably anything with a file raises this unhandled exception when the file is empty. Not sure if there are other types of "File Fields" but if there are, they probably all suffer from this.

**Comment by brodriguez8774** [comment]
Yes. I still think we should follow what was said in issue #14 . Now effectively merged into #4 .

That would handle for these kinds of unexpected errors. Or at least make sure we're aware of the most common ones.

**Comment by DJBarnes** [comment]
This should be fixed via the add_all_django_types_to_test_view branch. Yes. Horrible branch name. Lots of changes there though. Will allow the handling of unexpected exceptions while trying to get attributes for an object. Additionally adds a sample model and sample form to the sample view to allow manual testing of dumping all Django model field types. Should be able to be ported to actual automated tests fairly easily.
