### ISSUE TITLE
Improve the same object highlighting so that it is constrained to a single dump rather than page wide.

### ISSUE THREAD

**Issue by DJBarnes** [DJBarnes/django-dump-die#5]
Improve the same object highlighting so that it is constrained to a single dump rather than page wide.

Probably need to add some sort of unique identifier to each dumped object's classes and or ids and update the JS to use that identifier to keep things separate. May even be able to use the for loop counter for the main for loop as the identifier as it will be unique for each dumped object.

**Comment by DJBarnes** [comment]
This is sort of working. A number of times dumped counter was added to the unique to know. So, it works for all root objects but fails for any nested duplicate objects. Need to see about having dups append the dup number to all child attributes as well so that each dump is completely separate.

**Comment by brodriguez8774** [comment]
...don't we want this to be page-wide though? At least that's what I understood our conclusion from today to be, from earlier discussion.

**Comment by DJBarnes** [comment]
Potentially want to have different highlighting for duplicated nested objects. EX: a root object has two properties. Both properties point to the exact same instance of something else. To help identify when an object may have more references to something than what is needed. Would also help identify self-references easier. This should happen on a per dump basis I think. Meaning not page wide. May need more trial and error / discussion as it will be difficult to have two types of highlighting at the same time.

**Comment by DJBarnes** [comment]
Closing this as I don't think that we are going to do this and instead leave the highlighting the way that it is. Does not match Symfony / Laravels behavior, but should be fine so long as there aren't a ton of self-referential objects being dumped. Can be re-opened if opinions change.
